M48
; DRILL file {KiCad 9.0.6} date 2025-12-29T00:57:44+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-29T00:57:44+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X70.61Y-54.88
X76.39Y-54.88
T2
X55.0Y-55.0
X81.5Y-55.0
M30
