M48
; DRILL file {KiCad 9.0.6} date 2026-01-06T07:35:51+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-06T07:35:51+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X71.11Y-54.88
X76.89Y-54.88
T2
X66.5Y-53.0
X81.5Y-53.0
M30
